GET http://localhost:3001/api/notes/5

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "POSTMAN 6not is good in testing backend3",
    "important": "false"
}